### ISSUE TITLE
Problem locating stata-sfi.jar

### ISSUE THREAD

**Issue by smkraus** [epkugelmass/stata-translate#1]
Hi there,

Thanks for this package - which might be super useful for my research. I couldn't manage to install it because I couldn't locate the stata-sfi file. Did the file naming change?

Thanks for your help!

**Comment by epkugelmass** [comment]
Hi!

The stata-sfi.jar archive is distributed as part of the Stata installation. It's proprietary code (owned by StataCorp) and so I can't redistribute a copy with this plugin.

You may find the discussion here useful: https://www.statalist.org/forums/forum/general-stata-discussion/general/1322113-how-do-i-compile-java-plugins-for-stata

Elan

**Comment by smkraus** [comment]
Hi Elan, 
Thanks, I didn't know that - will look into it and report back in case of any problems.
Best,
Sebastian
